const data = {
  products: [
    {
      _id: "1",
      name: "Akun orb 10k",
      slug: "Akun-orb",
      category: "Akun orb",
      image: "/images/akunorb.PNG",
      price: 100,
      countInStock: 10,
      brand: "orb",
      rating: 4.5,
      numbreview: 2,
      description: "Hight amount orb",
    },
    {
      _id: "2",
      name: "Akun starter",
      slug: "Akun-starter",
      category: "Akun starter",
      image: "/images/akunstarter.PNG",
      price: 50,
      countInStock: 10,
      brand: "starter",
      rating: 4.5,
      numbreview: 3,
      description: "Starter with meta char",
    },
    {
      _id: "3",
      name: "Akun midgame",
      slug: "Akun-midgame",
      category: "Akun midgame",
      image: "/images/akunmidgame.PNG",
      price: 200,
      countInStock: 10,
      brand: "midgame",
      rating: 4.5,
      numbreview: 2,
      description: "account well build",
    },
    {
      _id: "4",
      name: "Akun endgame",
      slug: "Akun-endgame",
      category: "Akun endgame",
      image: "/images/akunendgame.PNG",
      price: 500,
      countInStock: 10,
      brand: "endgame",
      rating: 4.5,
      numbreview: 4,
      description: "accound godly build",
    },
  ],
};
export default data;
